apiVersion: v1
kind: ReplicationController
metadata:
  name: mynignxapp-rc
spec:
  replicas: 3    
  selector:
     app: mynignxapp
  template: 
   metadata: 
      labels:
         app: mynignxapp
   spec:
     containers:
     - name: nignx-container
       image: nignx
       ports:
        - containerPort: 8080

